import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, integer, time, date, uuid } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Users table (students and trainer)
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  phone: text("phone").notNull().unique(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name"),
  middleName: text("middle_name"),
  birthDate: text("birth_date"), // YYYY-MM-DD
  trainerNotes: text("trainer_notes"),
  parentFullName: text("parent_full_name"),
  parentPhone: text("parent_phone"),
  role: text("role").notNull().default("student"), // "student" or "trainer"
  isVerified: boolean("is_verified").notNull().default(false),
  verificationCode: text("verification_code"),
  password: text("password").notNull().default(""),
  mustChangePassword: boolean("must_change_password").notNull().default(false),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Consent documents managed by trainer (rules, agreements, etc.)
export const documents = pgTable("documents", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  title: text("title").notNull(),
  content: text("content").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// Records of which user accepted which document
export const userConsents = pgTable("user_consents", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  documentId: varchar("document_id").notNull().references(() => documents.id),
  acceptedAt: timestamp("accepted_at").defaultNow(),
});

// Time slots for the schedule (8:00-20:00)
export const timeSlots = pgTable("time_slots", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  date: date("date").notNull(), // YYYY-MM-DD
  time: time("time").notNull(), // HH:MM format (08:00, 09:00, etc.)
  maxCapacity: integer("max_capacity").notNull().default(2), // max 2 students per hour
  isBlocked: boolean("is_blocked").notNull().default(false), // trainer can block slots
  createdAt: timestamp("created_at").defaultNow(),
});

// Recurring booking rules (e.g. "every Tuesday and Thursday at 18:00")
export const recurringBookings = pgTable("recurring_bookings", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  studentId: varchar("student_id").notNull().references(() => users.id),
  weekdays: integer("weekdays").array().notNull(), // ISO day numbers 1..7 (Mon=1, Sun=7)
  hour: integer("hour").notNull(), // 8..19
  startDate: text("start_date").notNull(), // YYYY-MM-DD inclusive
  endDate: text("end_date"), // YYYY-MM-DD inclusive, nullable = open-ended
  createdBy: varchar("created_by").notNull().references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// Bookings table
export const bookings = pgTable("bookings", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  studentId: varchar("student_id").notNull().references(() => users.id),
  timeSlotId: varchar("time_slot_id").notNull().references(() => timeSlots.id),
  status: text("status").notNull().default("pending"), // "pending", "confirmed", "cancelled"
  bookedBy: varchar("booked_by").notNull().references(() => users.id), // who made the booking (student or trainer)
  notes: text("notes"), // trainer notes
  recurringBookingId: varchar("recurring_booking_id").references(() => recurringBookings.id), // if generated by a recurring rule
  createdAt: timestamp("created_at").defaultNow(),
  confirmedAt: timestamp("confirmed_at"),
  cancelledAt: timestamp("cancelled_at"),
});

// Notification system for trainer confirmations
export const notifications = pgTable("notifications", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  type: text("type").notNull(), // "booking_request", "booking_confirmed", "booking_cancelled"
  title: text("title").notNull(),
  message: text("message").notNull(),
  isRead: boolean("is_read").notNull().default(false),
  relatedBookingId: varchar("related_booking_id").references(() => bookings.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// Insert schemas
export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
  lastLogin: true,
});

export const insertTimeSlotSchema = createInsertSchema(timeSlots).omit({
  id: true,
  createdAt: true,
});

export const insertBookingSchema = createInsertSchema(bookings).omit({
  id: true,
  createdAt: true,
  confirmedAt: true,
  cancelledAt: true,
});

export const insertNotificationSchema = createInsertSchema(notifications).omit({
  id: true,
  createdAt: true,
});

export const insertDocumentSchema = createInsertSchema(documents).omit({
  id: true,
  createdAt: true,
});

export const insertUserConsentSchema = createInsertSchema(userConsents).omit({
  id: true,
  acceptedAt: true,
});

export const insertRecurringBookingSchema = createInsertSchema(recurringBookings).omit({
  id: true,
  createdAt: true,
});

// Validation schemas
export const phoneVerificationSchema = z.object({
  phone: z.string().regex(/^\+?[1-9]\d{1,14}$/, "Invalid phone number format"),
  code: z.string().length(6, "Verification code must be 6 digits"),
});

export const studentRegistrationSchema = z.object({
  phone: z.string().regex(/^\+?[1-9]\d{1,14}$/, "Invalid phone number format"),
  firstName: z.string().min(2, "First name must be at least 2 characters"),
  lastName: z.string().min(2, "Last name must be at least 2 characters"),
});

export const trainerLoginSchema = z.object({
  phone: z.string(),
  password: z.string().min(6, "Password must be at least 6 characters"),
});

export const bookingRequestSchema = z.object({
  timeSlotId: z.string(),
  notes: z.string().optional(),
});

// Inferred types
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertTimeSlot = z.infer<typeof insertTimeSlotSchema>;
export type TimeSlot = typeof timeSlots.$inferSelect;
export type InsertBooking = z.infer<typeof insertBookingSchema>;
export type Booking = typeof bookings.$inferSelect;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type Notification = typeof notifications.$inferSelect;
export type InsertDocument = z.infer<typeof insertDocumentSchema>;
export type Document = typeof documents.$inferSelect;
export type InsertUserConsent = z.infer<typeof insertUserConsentSchema>;
export type UserConsent = typeof userConsents.$inferSelect;
export type StudentWithConsents = User & { consents: (UserConsent & { document: Document })[] };
export type InsertRecurringBooking = z.infer<typeof insertRecurringBookingSchema>;
export type RecurringBooking = typeof recurringBookings.$inferSelect;

// Extended types for API responses
export type TimeSlotWithBookings = TimeSlot & {
  bookings: (Booking & { student: Pick<User, 'firstName' | 'lastName' | 'phone'> })[];
  availableSpots: number;
};

export type BookingWithDetails = Booking & {
  student: Pick<User, 'firstName' | 'lastName' | 'phone'>;
  timeSlot: TimeSlot;
};

export type DaySchedule = {
  date: string;
  timeSlots: TimeSlotWithBookings[];
};

// Phone verification types
export type PhoneVerification = z.infer<typeof phoneVerificationSchema>;
export type StudentRegistration = z.infer<typeof studentRegistrationSchema>;
export type TrainerLogin = z.infer<typeof trainerLoginSchema>;
export type BookingRequest = z.infer<typeof bookingRequestSchema>;